<div class="sidebar-ad-inner">
  <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6064212272457327"
     crossorigin="anonymous"></script>
  <!-- 侧边栏广告 -->
  <ins class="adsbygoogle"
      style="display:block"
      data-ad-client="ca-pub-6064212272457327"
      data-ad-slot="7700244708"
      data-ad-format="auto"
      data-full-width-responsive="true"></ins>
  <script>
      (adsbygoogle = window.adsbygoogle || []).push({});
  </script>
</div>